# Generated by Django 4.2.7 on 2023-12-05 21:35

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import underway_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(error_messages='invalid route name', validators=[django.core.validators.RegexValidator('[\\w]+', 'Invalid route name')])),
                ('description', models.TextField()),
                ('start_date', models.DateField(error_messages='invalid start date', validators=[underway_app.validators.validate_future_date, django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 12, 5))])),
                ('location', models.CharField(error_messages='invalid location')),
                ('duration', models.IntegerField(error_messages='invalid duration')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain', to=settings.AUTH_USER_MODEL)),
                ('crew', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
